# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

orbs:
  android: circleci/android@1.0.3

defaults: &defaults
    machine:
      image: android:202102-01
  # working_directory: ~/repo

ruby:
  docker:
    # Choose the version of Node you want here
    - image: circleci/ruby:latest
  working_directory: ~/repo

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run tests
          command: yarn test # this command will be added to/found in your package.json scripts

  android-alpha:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Fastlane alpha track
          command: bundle exec fastlane alpha

  android-beta:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Fastlane promote to beta track
          command: bundle exec fastlane beta

workflows:
  version: 2
  build-test-and-hold:
    jobs:
      - setup
      - tests:
          requires:
            - setup
      - android-alpha-hold:
          type: approval
      - android-beta-hold:
          type: approval
      - android-alpha:
          requires:
            - android-alpha-hold
          filters:
            tags:
              only: /^v.*/
      - android-beta:
          requires:
            - android-beta-hold
          filters:
            tags:
              only: /^v.*/
